services:
  - type: web
    name: sentinela-oeste
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python sentinela_api_v10.py
    healthCheckPath: /status
